### ISSUE TITLE
memorySize of the lambdas should be 128.

### ISSUE THREAD

**Issue by teebu** [alexcasalboni/aws-lambda-power-tuning#11]
There is no reason for the tester functions to be so big,

```
functions:
  initializer:
    handler: lambda/initializer.handler
    memorySize: 128
    timeout: 60
  executor:
    handler: lambda/executor.handler
    memorySize: 128
    timeout: 300
  cleaner:
    handler: lambda/cleaner.handler
    memorySize: 128
    timeout: 60
  finalizer:
    handler: lambda/finalizer.handler
    memorySize: 128
    timeout: 60
```
