### ISSUE TITLE
Restrict Lambda IAM permissions

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#5]
The current role has full access to AWS Lambda:

```yaml
iamRoleStatements:
    - Effect: Allow
      Action:
        - 'lambda:*'
      Resource: '*'
```

Since we want the lambdaARN to be given at runtime, we can't really restrict the Resource parameter. We could restrict the set of actions, though. Also, experienced users can always force Resource to be the Lambda Function(s) they want to optimize.

As far as actions are concerned, Initializer, Executor, Finalizer and Cleaner need the following Lambda permissions (only 7 out of [28](http://docs.aws.amazon.com/lambda/latest/dg/API_Operations.html)):

- GetAlias
- UpdateFunctionConfiguration
- PublishVersion
- DeleteFunction (always with Qualifier)
- CreateAlias
- DeleteAlias
- Invoke
