### ISSUE TITLE
Optionally configure a single Lambda ARN at deploy-time

### ISSUE THREAD

**Issue by alexcasalboni** [alexcasalboni/aws-lambda-power-tuning#52]
The current IAM statement for initializer, execution and optimizer looks like this:

```yaml
          Statement:
            - Effect: Allow
              Action:
                - lambda:GetAlias
                - lambda:PublishVersion
                - lambda:UpdateFunctionConfiguration
                - lambda:CreateAlias
                - lambda:UpdateAlias
              Resource: '*'
```

I think some security-concerned users would rather avoid that `Resource: '*'`.

We could allow them to optionally configure a Lambda ARN (or prefix) so that these IAM policies are a bit more fine-grained.

Technically, this would be a CFN Parameter (e.g. `lambdaResource`), directly referenced via `!Ref`.
